apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubebeat
subjects:
- kind: ServiceAccount
  name: kubebeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kubebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubebeat
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kubebeat
    namespace: kube-system
roleRef:
  kind: Role
  name: kubebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubebeat-kubeadm-config
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kubebeat
    namespace: kube-system
roleRef:
  kind: Role
  name: kubebeat-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
